provider:
  name: faas
  gateway: http://localhost:8080

functions:
  kubecon:
    lang: python
    handler: ./kubecon
    image: alexellis/kubecon
  dockercon-tester:
    lang: python
    handler: ./dockercon-tester
    image: dockercon-tester
